services:
  notify:
    build: .
    container_name: notify
    restart: unless-stopped
    environment:
      - RMQ_HOST=rabbitmq
      - RMQ_PORT=5672
      - RMQ_USER
      - RMQ_PASSWORD
      - RMQ_ROUTING_KEY
      - RMQ_QUEUE
      - RMQ_EXCHANGE
      - SMTP_USER
      - SMTP_PASSWORD
      - SMTP_FROM
    volumes:
      - notify_sqlite_data:/app/data
      - ./logs:/app/logs

volumes:
  notify_sqlite_data:
