services:
  notify:
    build: .
    container_name: notify
    environment:
      - RMQ_HOST=rabbitmq
      - RMQ_PORT=5672
      - RMQ_USER
      - RMQ_PASSWORD
      - SMTP_USER
      - SMTP_PASSWORD
      - SMTP_FROM
    volumes:
      - notify_sqlite_data:/app/data
      - ./logs:/app/logs
    networks:
      - aviatx-net
    restart: unless-stopped

volumes:
  notify_sqlite_data:

networks:
  aviatx-net:
    external: true
